version: "3"
services: 
 firefox:
    image: selenium/node-firefox-debug:3.141.59
    shm_size: 1gb
  test-module-firefox:
    image: deepikaarya/mydocker-myimage
    depends_on:
      - firefox
    environment:
      - BROWSER=firefox
      - MODULE=testng.xml
    volumes:
      - ./test-result-firefox:/Users/deearya/myShare/test-output